/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/accounts/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enable"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/accounts/{id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["assignRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/exam-versions/{examVersionId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateExamVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/exam-versions/{examVersionId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateExamVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/exam-versions/{examVersionId}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["setMappings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["renameTopic"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tracks"];
        put?: never;
        post: operations["createTrack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/tracks/{trackId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["track_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/tracks/{trackId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateTrack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/tracks/{trackId}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deactivateTrack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/tracks/{trackId}/exam-versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createExamVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/catalog/tracks/{trackId}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/question-revisions/{revisionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["edit"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/question-revisions/{revisionId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/question-revisions/{revisionId}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deprecate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/question-revisions/{revisionId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/question-revisions/{revisionId}/request-changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestChanges"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/question-revisions/{revisionId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submit_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/questions/{questionId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["newRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tracks_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/tracks/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["track"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/editorial/catalog/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["topics_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/rebuild": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rebuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/reconciliation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reconciliation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/progress/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["topics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/misconceptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["misconceptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/history/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["attempts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/history/mock-exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["mockExams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/history/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/mock-exams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["start_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/mock-exams/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["availability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/mock-exams/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/mock-exams/{sessionId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["finish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/mock-exams/{sessionId}/questions/{position}/response": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respond"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/mock-exams/{sessionId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["result"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/sessions/{sessionId}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abandon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/sessions/{sessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/study/sessions/{sessionId}/questions/{position}/attempt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post: operations["submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountView: {
            email: string;
            enabled: boolean;
            /** Format: uuid */
            id: string;
            permissions: string[];
            roles: string[];
        };
        AdminExamVersionView: {
            examCode: string | null;
            examName: string | null;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            javaRelease: number | null;
            label: string;
            objectivesUrl: string | null;
            status: string;
            topics: components["schemas"]["AdminMappingView"][];
        };
        AdminMappingView: {
            objectiveRef: string | null;
            /** Format: int32 */
            position: number;
            /** Format: uuid */
            topicId: string;
            /** Format: int32 */
            weight: number | null;
        };
        AdminTopicView: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            parentId: string | null;
            slug: string;
        };
        AdminTrackView: {
            certificationName: string | null;
            examVersions: components["schemas"]["AdminExamVersionView"][];
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
            provider: string | null;
            slug: string;
            status: string;
            topics: components["schemas"]["AdminTopicView"][];
        };
        Answer: {
            correctOptions: string[];
            explanation: string;
            options: components["schemas"]["OptionAnswer"][];
            references: components["schemas"]["Reference"][];
        };
        AttemptHistoryItem: {
            confidence: string;
            correct: boolean;
            /** Format: int64 */
            elapsedMillis: number;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            position: number;
            question: components["schemas"]["HistoricalQuestion"];
            selectedOptions: string[];
            /** Format: uuid */
            sessionId: string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: uuid */
            topicId: string;
        };
        AttemptRequest: {
            /** @enum {string} */
            confidence: "LOW" | "MEDIUM" | "HIGH";
            /** Format: int64 */
            elapsedMillis: number;
            selectedOptions: string[];
        };
        AttemptResult: {
            answer: components["schemas"]["Answer"];
            confidence: string;
            correct: boolean;
            /** Format: int64 */
            elapsedMillis: number;
            /** Format: int32 */
            position: number;
            /** Format: uuid */
            revisionId: string;
            selectedOptions: string[];
            /** Format: date-time */
            submittedAt: string;
        };
        AuditEventView: {
            action: string;
            /** Format: uuid */
            actorId: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            requestId: string | null;
            subject: string;
        };
        AuthorableTopic: {
            /** Format: int32 */
            depth: number;
            /** Format: uuid */
            id: string;
            name: string;
            objectiveRef: string | null;
            slug: string;
        };
        AuthorableTrack: {
            /** Format: uuid */
            id: string;
            kind: string;
            name: string;
            slug: string;
            status: string;
            topics: components["schemas"]["AuthorableTopic"][];
        };
        CountsView: {
            /** Format: int32 */
            attempted: number;
            /** Format: int32 */
            correct: number;
            /** Format: date-time */
            lastActivityAt: string;
        };
        CreateExamVersionRequest: {
            examCode: string;
            examName: string;
            /** Format: int32 */
            javaRelease?: number;
            label: string;
            objectivesUrl: string;
        };
        CreateTopicRequest: {
            name: string;
            /** Format: uuid */
            parentId?: string;
            slug: string;
        };
        CreateTrackRequest: {
            certificationName: string;
            name: string;
            provider: string;
            slug: string;
        };
        CsrfToken: {
            headerName: string;
            parameterName: string;
            token: string;
        };
        CsrfView: {
            headerName: string;
            token: string;
        };
        Difference: {
            expected: components["schemas"]["CountsView"];
            stored: components["schemas"]["CountsView"];
            /** Format: uuid */
            topicId: string;
        };
        ExamVersionView: {
            examCode: string;
            examName: string;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            javaRelease: number;
            label: string;
            objectivesUrl: string;
        };
        HistoricalOption: {
            correct: boolean;
            explanation: string;
            key: string;
            text: string;
        };
        HistoricalQuestion: {
            explanation: string;
            options: components["schemas"]["HistoricalOption"][];
            prompt: string;
            references: components["schemas"]["HistoricalReference"][];
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            revisionNumber: number;
            revisionStatus: string;
            type: string;
        };
        HistoricalReference: {
            title: string;
            url: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        MappingEntry: {
            objectiveRef: string;
            /** Format: int32 */
            position: number;
            /** Format: uuid */
            topicId: string;
        };
        Misconception: {
            /** Format: int32 */
            attempts: number;
            /** Format: date-time */
            lastAt: string;
            /** Format: int32 */
            questions: number;
            /** Format: uuid */
            topicId: string;
            topicName: string | null;
        };
        MockExamAvailability: {
            /** Format: uuid */
            activeSessionId: string | null;
            contentReady: boolean;
            /** Format: int32 */
            missingQuestionCount: number;
            /** Format: int32 */
            questionCount: number;
            /** Format: int32 */
            questionsPerTopic: number;
            topics: components["schemas"]["MockExamTopicAvailability"][];
        };
        MockExamHistoryItem: {
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            closedAt: string | null;
            /** Format: int32 */
            correctCount: number | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            id: string;
            passed: boolean | null;
            /** Format: int32 */
            passingPercentage: number;
            /** Format: int32 */
            percentage: number | null;
            /** Format: int32 */
            questionCount: number;
            status: string;
            topics: components["schemas"]["MockExamTopicHistoryItem"][];
            /** Format: uuid */
            trackId: string;
        };
        MockExamQuestionView: {
            answered: boolean;
            /** Format: int32 */
            position: number;
            question: components["schemas"]["PublishedQuestion"];
            /** Format: uuid */
            topicId: string;
        };
        MockExamResult: {
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            /** Format: int64 */
            elapsedSeconds: number;
            /** Format: uuid */
            id: string;
            passed: boolean;
            /** Format: int32 */
            passingCorrectCount: number;
            /** Format: int32 */
            passingPercentage: number;
            /** Format: int32 */
            percentage: number;
            questions: components["schemas"]["QuestionResult"][];
            status: string;
            topics: components["schemas"]["TopicResult"][];
            /** Format: int32 */
            total: number;
            /** Format: uuid */
            trackId: string;
        };
        MockExamStartRequest: {
            trackSlug: string;
        };
        MockExamTopicAvailability: {
            /** Format: int32 */
            available: number;
            /** Format: int32 */
            missing: number;
            /** Format: int32 */
            required: number;
            /** Format: uuid */
            topicId: string;
        };
        MockExamTopicHistoryItem: {
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            needsReview: boolean;
            /** Format: int32 */
            percentage: number;
            /** Format: uuid */
            topicId: string;
            /** Format: int32 */
            total: number;
        };
        MockExamView: {
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            closedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            passingPercentage: number;
            /** Format: int32 */
            questionCount: number;
            questions: components["schemas"]["MockExamQuestionView"][];
            status: string;
            /** Format: uuid */
            trackId: string;
        };
        OptionAnswer: {
            correct: boolean;
            explanation: string;
            key: string;
            text: string;
        };
        OptionRequest: {
            correct?: boolean;
            explanation?: string;
            key: string;
            text: string;
        };
        OptionView: {
            correct: boolean;
            explanation: string;
            key: string;
            text: string;
        };
        PageAttemptHistoryItem: {
            items: components["schemas"]["AttemptHistoryItem"][];
            nextCursor: string | null;
        };
        PageAuditEventView: {
            items: components["schemas"]["AuditEventView"][];
            nextCursor: string | null;
        };
        PageMockExamHistoryItem: {
            items: components["schemas"]["MockExamHistoryItem"][];
            nextCursor: string | null;
        };
        PageSessionHistoryItem: {
            items: components["schemas"]["SessionHistoryItem"][];
            nextCursor: string | null;
        };
        PublishedOption: {
            key: string;
            text: string;
        };
        PublishedQuestion: {
            /** @enum {string} */
            difficulty: "EASY" | "MEDIUM" | "HARD";
            /** Format: int32 */
            javaRelease: number;
            options: components["schemas"]["PublishedOption"][];
            prompt: string;
            /** Format: uuid */
            questionId: string;
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            revisionNumber: number;
            /** Format: uuid */
            topicId: string;
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE";
        };
        QuestionResult: {
            answer: components["schemas"]["Answer"];
            answered: boolean;
            correct: boolean;
            /** Format: int32 */
            position: number;
            question: components["schemas"]["PublishedQuestion"];
            selectedOptions: string[];
            /** Format: uuid */
            topicId: string;
        };
        QuestionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            latestRevisionId: string;
            /** Format: int32 */
            latestRevisionNumber: number;
            latestStatus: string;
            prompt: string | null;
            /** Format: uuid */
            topicId: string | null;
        };
        QuestionView: {
            /** Format: uuid */
            createdBy: string;
            /** Format: uuid */
            id: string;
            revisions: components["schemas"]["RevisionView"][];
        };
        Queue: {
            /** Format: int32 */
            dueNow: number;
            items: components["schemas"]["QueueItem"][];
            /** Format: int32 */
            neverAttempted: number;
            /** Format: int32 */
            waiting: number;
        };
        QueueItem: {
            lastAnswerCorrect: boolean;
            /** Format: date-time */
            lastAttemptedAt: string;
            prompt: string;
            /** Format: uuid */
            questionId: string;
            /** @enum {string} */
            reason: "WRONG_WHILE_CONFIDENT" | "WRONG" | "RIGHT_BUT_UNSURE" | "DUE_FOR_RECALL";
            /** Format: uuid */
            revisionId: string;
            /** Format: int32 */
            timesAttempted: number;
            /** Format: int32 */
            timesWrong: number;
            /** Format: uuid */
            topicId: string;
            topicName: string | null;
        };
        RebuildResult: {
            /** Format: int32 */
            corrected: number;
            /** Format: int32 */
            topics: number;
        };
        Reconciliation: {
            consistent: boolean;
            differences: components["schemas"]["Difference"][];
        };
        Reference: {
            title: string;
            url: string;
        };
        ReferenceRequest: {
            title: string;
            url: string;
        };
        ReferenceView: {
            title: string;
            url: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RenameTopicRequest: {
            name: string;
        };
        RequiredReviewRequest: {
            checklist?: string[];
            comment: string;
        };
        ResponseReceipt: {
            /** Format: int32 */
            position: number;
            /** Format: uuid */
            revisionId: string;
            selectedOptions: string[];
            /** Format: date-time */
            submittedAt: string;
        };
        ResponseRequest: {
            selectedOptions: string[];
        };
        ReviewRequest: {
            checklist?: string[];
            comment?: string;
        };
        ReviewView: {
            checklist: string[];
            comment: string | null;
            /** Format: date-time */
            decidedAt: string;
            decision: string;
            /** Format: uuid */
            reviewerId: string;
            reviewerName: string | null;
        };
        RevisionRequest: {
            /** @enum {string} */
            difficulty?: "EASY" | "MEDIUM" | "HARD";
            difficultyRationale?: string;
            explanation?: string;
            /** Format: int32 */
            javaRelease?: number;
            options?: components["schemas"]["OptionRequest"][];
            prompt?: string;
            references?: components["schemas"]["ReferenceRequest"][];
            /** @enum {string} */
            seniority?: "PLENO" | "SENIOR";
            /** Format: uuid */
            topicId?: string;
            /** @enum {string} */
            type: "SINGLE_CHOICE" | "MULTIPLE_CHOICE";
        };
        RevisionView: {
            /** Format: uuid */
            authorId: string;
            authorName: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            deprecatedAt: string | null;
            difficulty: string | null;
            difficultyRationale: string | null;
            /** Format: uuid */
            examVersionId: string | null;
            explanation: string | null;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            javaRelease: number | null;
            /** Format: int32 */
            number: number;
            options: components["schemas"]["OptionView"][];
            prompt: string | null;
            /** Format: date-time */
            publishedAt: string | null;
            /** Format: uuid */
            publishedBy: string | null;
            publishedByName: string | null;
            references: components["schemas"]["ReferenceView"][];
            reviews: components["schemas"]["ReviewView"][];
            seniority: string | null;
            status: string;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: uuid */
            topicId: string | null;
            type: string;
        };
        RolesRequest: {
            roles: ("LEARNER" | "EDITOR" | "REVIEWER" | "ADMINISTRATOR")[];
        };
        SessionHistoryItem: {
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            closedAt: string | null;
            /** Format: int32 */
            correctCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            requestedCount: number;
            status: string;
            /** Format: uuid */
            topicId: string;
        };
        SessionQuestionView: {
            answered: boolean;
            /** Format: int32 */
            position: number;
            question: components["schemas"]["PublishedQuestion"];
        };
        SessionSummary: {
            /** Format: int32 */
            answeredCount: number;
            /** Format: date-time */
            closedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            questionCount: number;
            status: string;
            /** Format: uuid */
            topicId: string;
        };
        SessionView: {
            /** Format: date-time */
            closedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: uuid */
            id: string;
            questions: components["schemas"]["SessionQuestionView"][];
            /** Format: int32 */
            requestedCount: number;
            status: string;
            /** Format: uuid */
            topicId: string;
        };
        SetMappingsRequest: {
            topics: components["schemas"]["MappingEntry"][];
        };
        StartRequest: {
            /** Format: int32 */
            questionCount?: number;
            revisionIds?: string[];
            /** Format: uuid */
            topicId: string;
        };
        TopicProgress: {
            accuracy: number | null;
            /** Format: int32 */
            attempted: number;
            /** Format: int32 */
            correct: number;
            /** Format: int32 */
            incorrect: number;
            /** Format: date-time */
            lastActivityAt: string | null;
            /** Format: uuid */
            topicId: string;
            topicName: string | null;
            trackSlug: string | null;
        };
        TopicResult: {
            /** Format: int32 */
            answered: number;
            /** Format: int32 */
            correct: number;
            /** Format: int32 */
            percentage: number;
            /** Format: uuid */
            topicId: string;
            /** Format: int32 */
            total: number;
        };
        TopicView: {
            /** Format: uuid */
            id: string;
            name: string;
            objectiveRef: string;
            slug: string;
            subtopics: components["schemas"]["TopicView"][];
        };
        TrackView: {
            certificationName: string;
            examVersion: components["schemas"]["ExamVersionView"];
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "CERTIFICATION" | "INTERVIEW";
            name: string;
            provider: string;
            slug: string;
            topics: components["schemas"]["TopicView"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    disable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
        };
    };
    enable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
        };
    };
    assignRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RolesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
        };
    };
    events: {
        parameters: {
            query?: {
                subject?: string;
                actorId?: string;
                action?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAuditEventView"];
                };
            };
        };
    };
    activateExamVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examVersionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    deactivateExamVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examVersionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    setMappings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                examVersionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetMappingsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    renameTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTopicRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    tracks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"][];
                };
            };
        };
    };
    createTrack: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTrackRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    track_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    activateTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    deactivateTrack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    createExamVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExamVersionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trackId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTopicRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminTrackView"];
                };
            };
        };
    };
    edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    deprecate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    requestChanges: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequiredReviewRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    submit_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                revisionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "DRAFT" | "TECHNICAL_REVIEW" | "APPROVED" | "PUBLISHED" | "DEPRECATED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionSummary"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    newRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["QuestionView"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query: {
                token: components["schemas"]["CsrfToken"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsrfView"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CSRF token missing or invalid */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountView"];
                };
            };
        };
    };
    tracks_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrackView"][];
                };
            };
        };
    };
    track: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TrackView"];
                };
            };
        };
    };
    topics_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorableTrack"][];
                };
            };
        };
    };
    rebuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RebuildResult"];
                };
            };
        };
    };
    reconciliation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Reconciliation"];
                };
            };
        };
    };
    topics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TopicProgress"][];
                };
            };
        };
    };
    misconceptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Misconception"][];
                };
            };
        };
    };
    queue: {
        parameters: {
            query?: {
                topicId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Queue"];
                };
            };
        };
    };
    attempts: {
        parameters: {
            query?: {
                topicId?: string;
                sessionId?: string;
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAttemptHistoryItem"];
                };
            };
        };
    };
    mockExams: {
        parameters: {
            query?: {
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageMockExamHistoryItem"];
                };
            };
        };
    };
    sessions: {
        parameters: {
            query?: {
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSessionHistoryItem"];
                };
            };
        };
    };
    start_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockExamStartRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MockExamView"];
                };
            };
        };
    };
    availability: {
        parameters: {
            query: {
                trackSlug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MockExamAvailability"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MockExamView"];
                };
            };
        };
    };
    finish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MockExamView"];
                };
            };
        };
    };
    respond: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                sessionId: string;
                position: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResponseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseReceipt"];
                };
            };
        };
    };
    result: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MockExamResult"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                status?: "IN_PROGRESS" | "COMPLETED" | "ABANDONED" | "EXPIRED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionSummary"][];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionView"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionView"];
                };
            };
        };
    };
    abandon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionView"];
                };
            };
        };
    };
    complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SessionView"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                position: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttemptResult"];
                };
            };
        };
    };
    submit: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
            };
            path: {
                sessionId: string;
                position: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AttemptResult"];
                };
            };
        };
    };
}
